### ISSUE TITLE
error: ‘chdir’ was not declared in this scope !

### ISSUE THREAD

**Issue by jnarayan81** [wyp1125/MCScanX#13]
jitendra@jitendra-UNLOCK-INSTALL[MCScanX] make                                                    []
g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc msa.cc permutation.cc -o MCScanX
msa.cc: In function ‘void msa_main(const char*)’:
msa.cc:289:22: error: ‘chdir’ was not declared in this scope
     if (chdir(html_fn)<0)
                      ^
makefile:2: recipe for target 'mcscanx' failed
make: *** [mcscanx] Error 1

**Comment by jebard** [comment]
I had this same problem - added this line to the top of "msa.cc"

#include <unistd.h>

**Comment by fearlessshi** [comment]
g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc msa.cc permutation.cc -o MCScanX
msa.cc: In function \u2018void msa_main(const char*)\u2019:
msa.cc:289:22: error: \u2018chdir\u2019 was not declared in this scope
     if (chdir(html_fn)<0)
                      ^
makefile:2: recipe for target 'mcscanx' failed
make: *** [mcscanx] Error 1
#Debian 9#
