### ISSUE TITLE
when using MCScanX_h 0 homologous pairs imported (316812 discarded)

### ISSUE THREAD

**Issue by tnaake** [wyp1125/MCScanX#14]
Dear Yupeng,

when I run `MCScanX_h data/at_gm_pt_vv`, where `at_gm_pt_vv.homology` only contains two columns (I deleted column 3 manually), I get the following output: 

Reading homologs and pre-processing
Generating homolog list
0 homologous pairs imported (316812 discarded)
0 pairwise comparisons
0 alignments generated
Pairwise collinear blocks written to ./at_gm_pt_vv.collinearity [1.861 seconds elapsed]
Writing multiple syntenic blocks to HTML files
at1.html
at2.html
...

Actually, I am expecting that I get similar results compared to the run where I have the third column with numerical values since in the manual (http://chibba.pgml.uga.edu/mcscan2/documentation/manual.pdf) it is described that you can pass a `.homology` file with two or three columns to `MCScanX_h`.

**Comment by charlesfeigin** [comment]
Hi tnaake, did you ever get an answer? I am running the program in the way described but it finishes almost instantaneously with nothing found. I have extremely reliable homology relationships in my .homology file and all files are formatted correctly as far as I can tell....

**Comment by charlesfeigin** [comment]
Hi @tnaake, did you ever get an answer? I am running the program in the way described but it finishes almost instantaneously with nothing found. I have extremely reliable homology relationships in my .homology file and all files are formatted correctly as far as I can tell....

**Comment by ViriatoII** [comment]
I have the same problem. It would be great for once to see an answer in this forum.......

**Comment by ViriatoII** [comment]
I had a similar problem that was solved by having a .gff file instead of .bed file in the directory:

> Sp1_Sp2.blast
Sp1_Sp2.gff
