### ISSUE TITLE
circle_plotter.java:232: error: cannot find symbol

### ISSUE THREAD

**Issue by yeswzc** [wyp1125/MCScanX#17]
Hi, I was compile the code downloaded from MCScanX home page. But it failed in making the programs under 'downstream_analyses' directory. Here is the message:

> 
> javac -g circle_plotter.java
> circle_plotter.java:232: error: cannot find symbol
>    Cubic xSpline = new Cubic(Cubic.BEZIER, GX);
>    ^
>   symbol:   class Cubic
>   location: class circle_plotter
> circle_plotter.java:232: error: cannot find symbol
>    Cubic xSpline = new Cubic(Cubic.BEZIER, GX);
>                        ^
>   symbol:   class Cubic
>   location: class circle_plotter
> circle_plotter.java:232: error: cannot find symbol
>    Cubic xSpline = new Cubic(Cubic.BEZIER, GX);
>                              ^
>   symbol:   variable Cubic
>   location: class circle_plotter
> circle_plotter.java:233: error: cannot find symbol
>    Cubic ySpline = new Cubic(Cubic.BEZIER, GY);
>    ^
>   symbol:   class Cubic
>   location: class circle_plotter
> circle_plotter.java:233: error: cannot find symbol
>    Cubic ySpline = new Cubic(Cubic.BEZIER, GY);
>                        ^
>   symbol:   class Cubic
>   location: class circle_plotter
> circle_plotter.java:233: error: cannot find symbol
>    Cubic ySpline = new Cubic(Cubic.BEZIER, GY);
>                              ^
>   symbol:   variable Cubic
>   location: class circle_plotter
> 6 errors
> make: *** [circle_plotter.class] Error 1

Could you help to solve this?
Thank you very much!

Best,
ZC

**Comment by qslin** [comment]
I have the same issue

**Comment by psimion** [comment]
And I also got the same issue.

**Comment by CourierFlag** [comment]
Same problem.
(-_-メ)　
Did you find a solution?

**Comment by zj-wien** [comment]
I also have this issue.

Could you help to solve this? thanks

**Comment by ijeremy** [comment]
Has anyone figured this out?

**Comment by xieduo7** [comment]
I have installed java-jdk8 but I still have this issue.

**Comment by kfuku52** [comment]
Same here. I tried to install MCScanX in a new conda environment (`conda create -n genespace orthofinder java-jdk==8.0.112`) and got the same error.

**Comment by libingtju** [comment]
Is there someone make it? Please give me your advice
