### ISSUE TITLE
MCScanX truncated results.

### ISSUE THREAD

**Issue by koushik1989** [wyp1125/MCScanX#25]
Dear developer and users, I am facing an issue while running MCScanX between two very closely related Drosophila species. I used blastp to blast proteins of each genome with itself and the target genome using " blastp -query -db -evalue 1e-10 -max_target_seqs 5 -outfmt 6 " and concatenated all 4 outputs generated using cat cmd. I concatenated the .gff from two genomes and ran MCScanX. The run completes without any errors but the collinearity file is incomplete with only 3 alignments. I have attached the output with this query. Kindly suggest where am I going wrong. I expect a high degree of collinearity between  the genomes as they are sibling species. My inputs are in following formats.  
I tried running blastall with the same protein files only to find the collinearity file with only 1 alignment. 

$ head Dnas_Dalb_mcscanX.blast 
XP_034100989.1	XP_034100989.1	100.000	18460	0	0	1	18460	1	18460	0.0	36057
XP_034100989.1	XP_034104103.1	27.285	1444	753	60	114	1461	195	1437	8.20e-67	255
XP_034100989.1	XP_034104103.1	27.795	1324	716	59	229	1461	148	1322	9.48e-64	245
XP_034100989.1	XP_034104103.1	29.673	1102	575	63	110	1172	420	1360	4.33e-60	233
XP_034100989.1	XP_034104103.1	26.980	745	362	32	90	697	738	1437	5.19e-36	153

$ head Dnas_Dalb_mcscanX.gff 
NC_047628.1	XP_034099297.1	24519288	24535641
NC_047628.1	XP_034100555.1	24538132	24554148
NC_047628.1	XP_034100562.1	24623105	24626154
NC_047628.1	XP_034099816.1	24628513	24629322
NC_047628.1	XP_034097326.1	24633653	24637715
[collinearity_file.txt](https://github.com/wyp1125/MCScanX/files/4937752/collinearity_file.txt)

Looking forward for a positive response.

thank you

**Comment by koushik1989** [comment]
I have solved the issue thank you.

**Comment by thesnakeguy** [comment]
Dear Koeshik1989, I am experiencing the same problem. How exactly did you fix this? Best regards.

**Comment by Surbhigrewal** [comment]
Can someone post a solution to this problem here? @koushik1989 @thesnakeguy

**Comment by fengzhiyue0710** [comment]
so do i,could you please post a solutiton here
