### ISSUE TITLE
Please fix the bug.

### ISSUE THREAD

**Issue by shenwei356** [wyp1125/MCScanX#4]
# compilation error

```
" msa.cc: In function ‘void msa_main(const char*)’:
msa.cc:289:22: error: ‘chdir’ was not declared in this scope
if (chdir(html_fn)<0)
^
make: *** [mcscanx] Error 1" 
"""
```
# Solution

http://ubuntuforums.org/showthread.php?t=2205151

if you are building on 64-bit you may need to add

```
#include <unistd.h>
```

to msa.h, dissect_multiple_alignment.h, and detect_collinear_tandem_arrays.h

**Comment by wyp1125** [comment]
This could be the problem of your C++ compiler. I suggest to use different
computers to have a try.

On Wed, Jan 7, 2015 at 12:53 AM, Wei Shen <notifications@github.com> wrote:

>                                 compilation error
>
>  " msa.cc: In function ‘void msa_main(const char
>
>
>
> *)’: msa.cc:289:22: error: ‘chdir’ was not declared in this scope if
> (chdir(html_fn)<0) ^ make: *** [mcscanx] Error 1"
>  Solution: http://ubuntuforums.org/showthread.php?t=2205151
>
> if you are building on 64-bit you may need to add
>
> #include
> to msa.h, dissect_multiple_alignment.h, and
> detect_collinear_tandem_arrays.h
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyp1125/MCScanx/issues/4>.
>



-- 
Yupeng Wang, Ph.D.
Research Fellow
Computational Biology Branch
NCBI, NLM, NIH
Bethesda, MD 20894

**Comment by shenwei356** [comment]
Thanks for you reply.

here is my gcc version:

$ gcc -v
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
--infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla
--enable-bootstrap --enable-shared --enable-threads=posix
--enable-checking=release --enable-multilib --with-system-zlib
--enable-__cxa_atexit --disable-libunwind-exceptions
--enable-gnu-unique-object --enable-linker-build-id
--with-linker-hash-style=gnu
--enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --enable-plugin
--enable-initfini-array --disable-libgcj
--with-isl=/builddir/build/BUILD/gcc-4.9.2-20141101/obj-x86_64-redhat-linux/isl-install
--with-cloog=/builddir/build/BUILD/gcc-4.9.2-20141101/obj-x86_64-redhat-linux/cloog-install
--enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686
--build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20141101 (Red Hat 4.9.2-1) (GCC)



沈伟 (Wei Shen)
Department of Microbiology, Third Military Medical University, China
Email: shenwei356@gmail.com
Site : http://shenwei.me

2015-01-17 21:35 GMT+08:00 Yupeng Wang <notifications@github.com>:

**Comment by jhh130910** [comment]
[root@localhost MCScanX]# make
g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc msa.cc permutation.cc -o MCScanX
g++ struct.cc mcscan_h.cc read_homology.cc out_homology.cc dagchainer.cc msa.cc permutation.cc -o MCScanX_h
g++ struct.cc dup_classifier.cc read_data.cc out_utils.cc dagchainer.cc cls.cc permutation.cc -o duplicate_gene_classifier
g++ dissect_multiple_alignment.cc -o downstream_analyses/dissect_multiple_alignment
g++ detect_collinear_tandem_arrays.cc -o downstream_analyses/detect_collinear_tandem_arrays
cd downstream_analyses/ && make
make[1]: Entering directory `/home/jhh130910/genome_analysis/MCScanX/downstream_analyses'
javac -g Cubic.java
make[1]: execvp: javac: Permission denied
make[1]: *** [Cubic.class] Error 127
make[1]: Leaving directory `/home/jhh130910/genome_analysis/MCScanX/downstream_analyses'
make: *** [mcscanx] Error 2

**Comment by jhh130910** [comment]
I have add #include <unistd.h> to  msa.h, dissect_multiple_alignment.h, and detect_collinear_tandem_arrays.h ,but get a new error message, what can I do next step ?

**Comment by jhh130910** [comment]
got it ,my java not correct ,solve it ,thanks!!

**Comment by officiant** [comment]
@jhh130910 I also get new error 
detect_collinear_tandem_arrays.cc:286:46: error: ‘getopt’ was not declared in this scope
detect_collinear_tandem_arrays.cc:291:32: error: ‘optarg’ was not declared in this scope
detect_collinear_tandem_arrays.cc:307:17: error: ‘optopt’ was not declared in this scope

do you know how to solve ? thank U

**Comment by wyp1125** [comment]
I am not sure if the package on github is the final version. Please
download it from http://chibba.pgml.uga.edu/mcscan2/

**Comment by jhh130910** [comment]
sorry,I can’t solve it.

**Comment by wyp1125** [comment]
Please download mcscanx from its homepage and recompile. GitHub version is incomplete

**Comment by dcopetti** [comment]
Hello,
The same problem still occurs if you download the software now, but here
https://ubuntuforums.org/showthread.php?t=2205151
the post #6 has the solution.
