### ISSUE TITLE
MCScanX Error - Can't plot the graphs (Downstream analysis)

### ISSUE THREAD

**Issue by tangtan** [wyp1125/MCScanx#6]
Hi,
I am trying to use the MCScanX tool(the latest release) for ploting circular displays of syntenic genomic blocks and I am using CentOS 7 with Java version:
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
When I tried running $ java circle_plotter -g gff_file -s collinearity_file -c control_file -o output_PNG_file
`[tt@localhost downstream_analyses]$ java circle_plotter -g ../MADS/MADS.gff -s ../MADS/MADS.collinearity -c circle.ctl -o MADS.png`
I got the following error message: 
```
Exception in thread "main" java.lang.NullPointerException
        at circle_plotter.paint(circle_plotter.java:142)
        at circle_plotter.main(circle_plotter.java:262)
```
Then I tried another drawing tool _dual_synteny_plotter_ and I still got the error message:
```
[tt@localhost downstream_analyses]$ java dual_synteny_plotter -g ../MADS/MADS.gff -s ../MADS/MADS.collinearity -c dual_synteny.ctl -o dual_synteny.PNG
Exception in thread "main" java.lang.NullPointerException
        at dual_synteny_plotter.paint(dual_synteny_plotter.java:148)
        at dual_synteny_plotter.main(dual_synteny_plotter.java:265)
```

Do you know how to solve it? All [data](https://github.com/tangtan/MADS) are stored in my repo.
Many thanks in advance.

**Comment by tangtan** [comment]
It seems that I forget to change the circle.ctl file. After I specified what genes should the plotter draw, I got the output png file successfully. The revised circle.ctl:
```
1600	//plot width and height (in pixels)
Chr1,Chr2,Chr3,Chr4,Chr5,Chr6,Chr7,Chr8,Chr9,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17	//chromosomes in the circle
```
The data can be found in my repo.
Thanks

**Comment by biolxy** [comment]
me to， Have you solved it ？

**Comment by biolxy** [comment]
我改过control文件后依旧提示
Exception in thread "main" java.lang.NullPointerException
        at circle_plotter.paint(circle_plotter.java:142)
        at circle_plotter.main(circle_plotter.java:262)
用了你的例子也不行0.0

**Comment by tangtan** [comment]
一个可能的原因是你修改的control文件与你数据本身不匹配，比如你想画A, B, C（control文件）但数据文件里却是D, E,
F。这样子java会抛出异常，我之前就是这个问题。你可以检查下你数据，也有可能是其他原因，但我就不清楚了。。。

**Comment by biolxy** [comment]
谢谢！

**Comment by zengxiaofei** [comment]
@biolxy 

Make sure that the `chromosome IDs` are separated by commas with no spaces. Besides, the separator between `chromosome IDs` and annotation `//chromosomes....` must be `TAB`, not `SPACE`, or you can simply remove the `annotation.`

Xiaofei

**Comment by Saadserfraz** [comment]
Hi @tangtan, 
I am bit new to MCScanX can you tell how can I make custom gff file for MCScanX, I tried parsing gff3 file but it did not worked as it doesn't contain .1 at the end of gene names.

**Comment by bioinfx** [comment]
I removed the annotation content (//chromosomes....), then it run smoothly.

**Comment by bioinfx** [comment]
Met this issue agian today. Unkown reasons.

---
```
java circle_plotter -g $PATH_TO.gff -s $PATH_TO.collinearity -c $PATH_TOdot.ctl -o $PATH_TO/output_PNG_file.png
Exception in thread "main" java.lang.NullPointerException
        at circle_plotter.paint(circle_plotter.java:142)
        at circle_plotter.main(circle_plotter.java:262)
```
