### ISSUE TITLE
Can not find source code to download

### ISSUE THREAD

**Issue by jiangqiuqiuu** [wyp1125/MCScanX#70]
Hi there,

I am having a problem accessing this link here ([chibba.pgml.uga.edu/mcscan2/](http://chibba.pgml.uga.edu/mcscan2/)) that I can not download the package to unzip. Please let me know where I can get the zipped packages. Thanks!

Cheers
Qiuyu

**Comment by tallnuttrbgv** [comment]
This site cannot be reached.
