### ISSUE TITLE
Where is MCScanX.zip ??

### ISSUE THREAD

**Issue by tallnuttrbgv** [wyp1125/MCScanX#73]
I cannot see MCScanX.zip anywhere?

**Comment by tonyaseverson** [comment]
You can download the zip file by clicking the green Code button, then clicking at the bottom of the popup where it says Download Zip. Or you can git clone the repo, too.

![Screenshot from 2024-02-19 23-19-44](https://github.com/wyp1125/MCScanX/assets/13499473/9486fa21-e7d7-4dd0-99e6-4abdb64b52ba)

**Comment by tallnuttrbgv** [comment]
Ah ok, I'm used to just having the install instructions say 'git clone ...'  The current instructions give the impression that it is a separate binary.

Thanks.
